version: '3.3'

#volumes:
#  persistent-data:

services:

  clouddump-debian:
    build:
      context: ../
      dockerfile: dockerfile-debian/Dockerfile
    devices:
    - /dev/fuse:/dev/fuse
    cap_add:
    - DAC_READ_SEARCH
    - SYS_ADMIN
    volumes:
    #- persistent-data:/persistent-data
    - ../config:/config
    - /srv/azdump:/azdump
    - /srv/pgdump:/pgdump

  clouddump-ubuntu:
    build:
      context: ../
      dockerfile: dockerfile-ubuntu/Dockerfile
    devices:
    - /dev/fuse:/dev/fuse
    cap_add:
    - DAC_READ_SEARCH
    - SYS_ADMIN
    volumes:
    #- persistent-data:/persistent-data
    - ../config:/config
    - /srv/azdump:/azdump
    - /srv/pgdump:/pgdump

  clouddump-fedora:
    build:
      context: ../
      dockerfile: dockerfile-fedora/Dockerfile
    devices:
    - /dev/fuse:/dev/fuse
    cap_add:
    - DAC_READ_SEARCH
    - SYS_ADMIN
    volumes:
    #- persistent-data:/persistent-data
    - ../config:/config
    - /srv/azdump:/azdump
    - /srv/pgdump:/pgdump

  clouddump-opensuse:
    build:
      context: ../
      dockerfile: dockerfile-opensuse/Dockerfile
    devices:
    - /dev/fuse:/dev/fuse
    cap_add:
    - DAC_READ_SEARCH
    - SYS_ADMIN
    volumes:
    #- persistent-data:/persistent-data
    - ../config:/config
    - /srv/azdump:/azdump
    - /srv/pgdump:/pgdump
